---
- hosts: appservers
  become: yes
  tasks:
  - name: pinging
    ping: 
  - name: install java on debian OS
    apt:
      name: "{{installjavadebian}}"
      state: present

  - name: install java on amazon linux OS
    dnf:
      name: "{{installjavaamazon}}"
      state: present
    when: ansible_os_family=="Amazon"

  