---
- hosts: appservers
  become: yes
  tasks:
  - name: pinging
    ping: 
    
  - name: install java on debian OS
    apt:
      name: "{{installjavadebian}}"
      state: absent
    when: ansible_os_family=="Debian"

  
  - name: install tree on amazon linux OS
    yum:
      name: tree
      state: present
    when: ansible_os_family=="Amazon"

  