---
- hosts: appservers
  become: yes
  tasks:
  - name: pinging
    ping: 
  - name: install java on debian OS
    apt:
      name: "{{installjavadebian}}"
      state: present

  - name: updating amazon linux
    ansible.builtin.yum:
      name: '*'
      state: latest
      update_cache: yes
    when: ansible_os_family=="Amazon"
  - name: install java on amazon linux OS
    yum:
      name: tree
      state: present
    when: ansible_os_family=="Amazon"

  