---
- hosts: appservers
  become: yes
  tasks:
  - name: pinging
    ping: 
  - name: install java on debian OS
    apt:
      name: "{{installjavadebian}}"
      state: absent
  - name: install java on amazon linux OS
    yum:
      name: "{{installjavaamazon}}"
      state: present
      use_backend: yum
  - name: install java on redhat os
    dnf:
      name: "{{installjavaredhat}}"
      state: present
  