---
- hosts: all
  become: yes
  tasks:
  - name: pinging....
    ping:
  - name: install apache2
    apt:
      name: apache2
      state: absent
  - name: tree 
    apt:
      name: tree
      state: absent
   

