---
- hosts: all
  become: yes
  tasks:
  - name: pinging....
    ping:
  - name: install apache2
    apt:
      name: apache2
      state: present
      when: ansible_os_family == 'amazon'
  - name: tree 
    apt:
      name: tree
      state: absent
   

