---
- hosts: all
  become: yes
  tasks:
  - name: pinging....
    ping:
  - name: install apache2
    yum:
      name: apache2
      state: present
      when: ansible_os_family=="Amazon"
  - name: tree 
    apt:
      name: tree
      state: absent
   

