---
- hosts: appservers
  become: yes
  tasks:
  - name: ping
    ping:
  - name: install apache2
    apt:
      name: "{{mywebpackdebian}}"
      state: present
    when: ansible_os_family=="Debian"
  - name: install httpd
    yum:
      name: "{{mywebpackredhat}}"
      state: present
    when: ansible_os_family=="Amazon"